services:
  - type: web
    name: instituto-app
    env: python
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: instituto-db
          property: connectionString

databases:
  - name: instituto-db
    databaseName: instituto
    plan: free 